### PR TITLE
65 download table

### PR DESCRIPTION
**Pull request by plocket**
Put send button on same line as email input, hopefully resolving some send button height issues.

### CODE REVIEW

**Review by purplesky2016 — COMMENTED** [review]
In desktop view the send button is on the same line as the email address, but not in mobile.

image

**Comment by plocket** [comment]
Great find, @purplesky2016 . What is the width of that mobile device?

**Comment by plocket** [comment]
Also, can you double check that you've pulled in this branch. In my version, when the header text is that wide, the send button is on the same line as the input.

**Comment by BryceStevenWilley** [comment]
I can't reproduce Lily's issue: the send button only goes to the next line when the screen is <= 292 pixels, which seems right, that's a very narrow screen. Works like that for me on Firefox and Chromium. `¯\_ (ツ)_/¯`

Screenshot from 2021-06-01 11-56-01

**Review by BryceStevenWilley — APPROVED** [review]
LGTM!

**Pull request merged**
