### PR TITLE
Safer idempotent email template

### PR DESCRIPTION
**Pull request by nonprofittechy**
We were running into a problem where an interview that used `x.send_email()` without defining `users[0].name.first` would silently fail. It seems that an action needs to be idempotent as far as gathering information that the user inputs, but it can safely trigger code blocks that aren't defined yet.

Took the chance to also slightly clean up the template. We were using `metadata_title` which obscurely used a title defined in the "first" entry in the `interview_metadata` dictionary. That variable wasn't visibly used anywhere else and would be hard to relate to the actual interview someone is running. Also added the new `AL_ORGANIZATION_HOMEPAGE` to the bottom of the email template and made it possible to customize just the `document_label` on a per-bundle basis without having to create your own email template.

Sample interview that can trigger the failed behavior on old AssemblyLine: (uncommenting lines for `users[0]` should let it succeed, but that shouldn't be required)

```yaml
---
include:
  - docassemble.AssemblyLine:al_package_unstyled.yml
---
objects:
  - test_doc: ALStaticDocument.using(filename="help_for_obligor_parents.pdf", enabled=True, title="ABC")
---
objects:
  - test_bundle: ALDocumentBundle.using(filename="download", title="bundle", enabled=True, elements=[test_doc])
---
#mandatory: True
#code: |
#  users[0] = ALIndividual(name=IndividualName(first="Bob", last="smith"))
#  users.there_is_another=False
---
mandatory: True
question: |
  Send me
subquestion: |
  ${ test_bundle.send_button_html() }
```

This resolves a production bug in https://courtformsonline.org/income/#child_support_obligor

### CODE REVIEW

**Comment by plocket** [comment]
Right at the moment, using that code I get this error on the screen:
```
Call to pdftk failed for concatenation where arguments were pdftk /tmp/playgroundstatic/12/ALDocsEmail/help_for_obligor_parents.pdf cat output /tmp/datempmzbir3jy.pdf
```

I'm pretty sure a moment ago I pressed 'Send' and didn't get an error (though I haven't gotten the email either), but if I didn't imagine that, it's different now.

**Comment by nonprofittechy** [comment]
You will need the template too, in data/static

**Comment by plocket** [comment]
Had to change the reference to the package to the local one. It then didn't send me the document I had anticipated, but it didn't ask me my username. My code was

```yml
---
include:
  - al_package_unstyled.yml
---
objects:
  - test_doc: ALStaticDocument.using(filename="test_alexhibit_pdf_1.pdf", enabled=True, title="ABC")
---
objects:
  - test_bundle: ALDocumentBundle.using(filename="download", title="bundle", enabled=True, elements=[test_doc])
---
#mandatory: True
#code: |
#  users[0] = ALIndividual(name=IndividualName(first="Bob", last="smith"))
#  users.there_is_another=False
---
mandatory: True
question: |
  Send me
subquestion: |
  ${ test_bundle.send_button_html() }
```

I had added test_alexhibit_pdf_1.pdf to the Static folder. That file was
[test_alexhibit_pdf_1.pdf](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/files/7781417/test_alexhibit_pdf_1.pdf)

The file I got in my email was
[file.pdf](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/files/7781419/file.pdf)

It's unlikely to be related and maybe I'm forgetting something about our `aldocument` behavior, so sorry about that.

**Review by plocket — COMMENTED** [review]
Looking great. If the file-mixup issue isn't related, this looks ready to merge, but I'll leave it up to you.

**Comment by nonprofittechy** [comment]
Have to admit I'm not quite sure what exact issue you ran into or how you tested, but as you said this change doesn't have any nexus. Usually the wrong file appearing is from a database rollback. That did happen last week so that's the likely cause.

**Pull request merged**
