### PR TITLE
Fix <div class="al_email_container">

### LINKED ISSUE #65: Attachment download table still needs some work
The buttons look fine vertically aligned, but without a description the placement of the form name is not quite right.

image

1. The name of the file should be top aligned and a bit larger
2. There needs to be something to fill the whitespace--could make the buttons horizontal again as one solution.

There could be other fixes to this page too. It just feels a bit awkward still.

### PR DESCRIPTION
**Pull request by purplesky2016**
Close #65. Replace pull #155.

### CODE REVIEW

**Comment by nonprofittechy** [comment]
Buttons still don't look right to me when I pull this into my playground. Any ideas?

image

**Comment by nonprofittechy** [comment]
It's the right css for sure. Only thought is you mentioned al_document.css, but the CSS file is named aldocument.css? But I can see the changes you mentioned on Teams.

**Comment by purplesky2016** [comment]
I am going to retract the css changes as the main goal here is to fix the py.

**Comment by nonprofittechy** [comment]
Still seeing very different output on my playground after creating a new project and pulling in. Someone else want to take a look? I may be doing something wrong. @plocket ?

**Comment by plocket** [comment]
For me, the table buttons are on the same line, but the 'Send' button is very tall and alignment is off at the start of the line. I can take a look to see if I can tweak a couple things.

**Comment by plocket** [comment]
In order to get the alignment to work correctly, I need to know if we're going to keep the send button on the same line as the email input (created that way from UX designer feedback) or if we're going to put it on a separate line.

**Pull request merged**
